[2025-03-18 22:21:03,155] #DEBUG conf.py (53): logger active
[2025-03-18 22:21:03,414] #DEBUG conf_redis.py (14): Установленно соединение с redis://localhost:6379
[2025-03-18 22:21:03,418] #DEBUG conf_redis.py (14): Установленно соединение с redis://localhost:6379
[2025-03-18 22:21:03,670] #DEBUG set_mongodb.py (29): Установлено подключение к MongoDB
[2025-03-18 22:21:11,269] #DEBUG vgpgk.py (134): замены для ИБ-211 взяты из кеша: 3, 4 п. БЖ
Гончаренко, 102
[2025-03-18 22:21:32,158] #DEBUG vgpgk.py (139): ИБ-231
[2025-03-18 22:21:32,159] #DEBUG vgpgk.py (141): ТЕКСТ: ИБ-231
СТРОКА:0 СТОБЕЦ 0
[2025-03-18 22:21:32,160] #DEBUG vgpgk.py (139): ИБ-231
[2025-03-18 22:21:32,161] #DEBUG vgpgk.py (141): ТЕКСТ: ИБ-231
СТРОКА:0 СТОБЕЦ 1
[2025-03-18 22:21:32,162] #DEBUG vgpgk.py (139): ИБ-221
[2025-03-18 22:21:32,163] #DEBUG vgpgk.py (141): ТЕКСТ: ИБ-221
СТРОКА:0 СТОБЕЦ 2
[2025-03-18 22:21:32,164] #DEBUG vgpgk.py (139): ИБ-221
[2025-03-18 22:21:32,165] #DEBUG vgpgk.py (141): ТЕКСТ: ИБ-221
СТРОКА:0 СТОБЕЦ 3
[2025-03-18 22:21:32,166] #DEBUG vgpgk.py (139): ИБ-211
[2025-03-18 22:21:32,167] #DEBUG vgpgk.py (141): ТЕКСТ: ИБ-211
СТРОКА:0 СТОБЕЦ 4
[2025-03-18 22:21:32,169] #INFO vgpgk.py (147): для группы ИБ-211 найдены замены 3, 4 п. БЖ
Гончаренко, 102
[2025-03-18 22:21:51,363] #DEBUG vgpgk.py (134): замены для ИБ-211 взяты из кеша: 3, 4 п. БЖ
Гончаренко, 102
